format_version: 3
pipelines:
  ohai:
    group: ohai
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/coryleeio/ohai.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - defaultStage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          defaultJob:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - exec:
                command: whoami
                run_if: passed
